package com.langtuo.teamachine.internal.constant;

public enum ErrorCodeEnum {
    // 测试
    TEST_ERR_ONLY_TEST("TEST_ERR_ONLY_TEST"),

    // 登录错误
    LOGIN_ERR_UNAUTHENTICATED("LOGIN_ERR_UNAUTHENTICATED"),
    LOGIN_ERR_UNAUTHORIZED("LOGIN_ERR_UNAUTHORIZED"),

    // 业务逻辑错误
    // 通用
    BIZ_ERR_ILLEGAL_ARGUMENT("BIZ_ERR_ILLEGAL_ARGUMENT"),
    BIZ_ERR_UPLOAD_FILE_IS_EMPTY("BIZ_ERR_UPLOAD_FILE_IS_EMPTY"),
    BIZ_ERR_PARSE_UPLOAD_FILE_ERROR("BIZ_ERR_PARSE_UPLOAD_FILE_ERROR"),
    BIZ_ERR_OBJECT_CODE_DUPLICATED("BIZ_ERR_OBJECT_CODE_DUPLICATED"),
    BIZ_ERR_OBJECT_NAME_DUPLICATED("BIZ_ERR_OBJECT_NAME_DUPLICATED"),
    BIZ_ERR_OBJECT_NOT_FOUND("BIZ_ERR_OBJECT_NOT_FOUND"),
    BIZ_ERR_CANNOT_DELETE_USING_OBJECT("BIZ_ERR_CANNOT_DELETE_USING_OBJECT"),
    // userSet
    BIZ_ERR_CANNOT_GET_LOGIN_ADMIN("BIZ_ERR_CANNOT_GET_LOGIN_ADMIN"),
    BIZ_ERR_CANNOT_DELETE_USING_ROLE("BIZ_ERR_CANNOT_DELETE_USING_ROLE"),
    BIZ_ERR_CANNOT_MODIFY_TENANT_SUPER_ADMIN_ROLE("BIZ_ERR_CANNOT_MODIFY_TENANT_SUPER_ADMIN_ROLE"),
    // shopSet
    BIZ_ERR_CANNOT_DELETE_USING_SHOP_GROUP("BIZ_ERR_CANNOT_DELETE_USING_SHOP_GROUP"),
    // deviceSet
    BIZ_ERR_CANNOT_DELETE_USING_MODEL("BIZ_ERR_CANNOT_DELETE_USING_MODEL"),
    BIZ_ERR_DEPLOY_CODE_DUPLICATED("BIZ_ERR_DEPLOY_CODE_DUPLICATED"),
    BIZ_ERR_DEPLOY_MACHINE_NOT_MATCH("BIZ_ERR_DEPLOY_MACHINE_NOT_MATCH"),
    // drinkSet
    BIZ_ERR_CANNOT_DELETE_USING_TOPPING_TYPE("BIZ_ERR_CANNOT_DELETE_USING_TOPPING_TYPE"),
    BIZ_ERR_CANNOT_DELETE_USING_TOPPING("BIZ_ERR_CANNOT_DELETE_USING_TOPPING"),
    BIZ_ERR_CANNOT_DELETE_USING_SPEC("BIZ_ERR_CANNOT_DELETE_USING_SPEC"),
    BIZ_ERR_CANNOT_DELETE_USING_TEA_TYPE("BIZ_ERR_CANNOT_DELETE_USING_TEA_TYPE"),
    BIZ_ERR_CANNOT_DELETE_USING_TEA("BIZ_ERR_CANNOT_DELETE_USING_TEA"),
    // menuSet
    BIZ_ERR_CANNOT_DELETE_USING_SERIES("BIZ_ERR_CANNOT_DELETE_USING_SERIES"),
    // reportSet
    BIZ_ERR_CANNOT_CALC_REPORT_FOR_NOW("BIZ_ERR_CANNOT_CALC_REPORT_FOR_NOW"),

    // 数据库错误
    DB_ERR_SELECT_FAIL("DB_ERR_QUERY_FAIL"),
    DB_ERR_INSERT_FAIL("DB_ERR_INSERT_FAIL"),
    DB_ERR_UPDATE_FAIL("DB_ERR_UPDATE_FAIL"),
    ;

    /**
     * 错误编码
     */
    private String errorCode;

    ErrorCodeEnum(String errorCode) {
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }
}
